import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import Image from "next/image";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--color-background)] font-sans selection:bg-[var(--color-primary-gold)] selection:text-[var(--color-surface)]">
      <div className="max-w-3xl mx-auto px-6 py-20">
        <Link href="/" className="inline-flex items-center gap-2 mb-12 text-[var(--color-muted-text)] hover:text-[var(--color-primary-text)] transition-colors text-sm font-medium">
          <ArrowLeft size={16} />
          Return to LegalVault
        </Link>
        
        <div className="flex items-center gap-4 mb-10">
          <Image src="/logo.png" alt="LegalVault Logo" width={40} height={40} className="object-contain" />
          <h1 className="text-4xl font-serif font-bold text-[var(--color-primary-text)] tracking-tight">Terms of Service</h1>
        </div>

        <div className="space-y-10 text-[var(--color-muted-text)] leading-relaxed text-[15px]">
          
          <section>
            <p className="mb-4">
              Welcome to LegalVault. By accessing or using the LegalVault service ("Service"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--color-primary-text)] mb-3">1. Nature of the Service</h2>
            <p>
              LegalVault is a software demonstration project built to showcase AI-assisted contract analysis and blockchain-based digital signatures. It is not an established legal institution, nor is it a legally certified service. The tools provided are intended for informational and operational demonstration purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--color-primary-text)] mb-3">2. Account Responsibilities</h2>
            <p>
              You are responsible for safeguarding your authentication credentials. You must notify us immediately of any unauthorized use of your account. You agree not to use the Service for any unlawful purpose, to upload malicious code, or to interfere with the integrity of the platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--color-primary-text)] mb-3">3. Contract Uploads & User Content</h2>
            <p>
              You retain ownership of any documents or contracts you upload. By uploading a document, you grant LegalVault the right to process it strictly for providing the Service (e.g., text extraction, AI analysis, hashing, and signature execution). You represent that you have the legal right to upload and process these documents.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--color-primary-text)] mb-3">4. AI-Assisted Analysis</h2>
            <p>
              The AI analysis generated by LegalVault is provided "AS IS." The analysis does not constitute legal advice and cannot replace the counsel of a qualified legal professional. You acknowledge that AI output may be incomplete or inaccurate, and you are solely responsible for reviewing your contracts.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--color-primary-text)] mb-3">5. Electronic Signatures and Verification</h2>
            <p>
              While LegalVault provides mechanisms for digital signatures and blockchain-based cryptographic verification, we do not guarantee that these signatures or verification records will be recognized as legally binding or enforceable in every jurisdiction. The legal enforceability of any contract executed via LegalVault depends on applicable local laws and the mutual agreement of the signing parties.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--color-primary-text)] mb-3">6. Service Availability & Security</h2>
            <p>
              The Service is provided on an "AS IS" and "AS AVAILABLE" basis. While we strive to maintain reasonable security measures, we do not guarantee that the Service will be uninterrupted, error-free, or completely secure. We reserve the right to modify, suspend, or discontinue any part of the Service at any time without notice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-[var(--color-primary-text)] mb-3">7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, in no event shall LegalVault or its creators be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising out of your access to, use of, or inability to use the Service.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
